# Generated by Django 3.0.5 on 2020-05-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200509_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_solver',
            field=models.BooleanField(default=False, help_text='Designates whether the user can view and rate problems', verbose_name='testsolver status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(default=False, help_text='Designates whether the user can submit problems to the database', verbose_name='problem writer status'),
        ),
    ]
