# Generated by Django 3.0.5 on 2020-05-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200509_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_new',
            field=models.BooleanField(default=True, help_text='Only true before permissions have been assigned', verbose_name='new account'),
        ),
    ]
