# Generated by Django 3.0.5 on 2020-05-01 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('problem_text', models.CharField(max_length=5000)),
                ('answer', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=10000)),
                ('difficulty', models.FloatField()),
                ('difficulty_votes', models.IntegerField()),
                ('quality', models.FloatField()),
                ('quality_votes', models.IntegerField()),
                ('update_time', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
