# Generated by Django 3.0.5 on 2020-05-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200501_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
