# Generated by Django 3.0.5 on 2020-05-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200514_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='subject',
            field=models.CharField(choices=[('alg', 'Algebra'), ('nt', 'Number Theory'), ('geo', 'Geometry'), ('combo', 'Combinatorics'), ('cs', 'Computer Science'), ('other', 'Other')], default='other', max_length=5),
            preserve_default=False,
        ),
    ]
