# Generated by Django 3.0.5 on 2020-05-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_problem_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='subject',
            field=models.CharField(choices=[('', 'Choose...'), ('alg', 'Algebra'), ('nt', 'Number Theory'), ('geo', 'Geometry'), ('combo', 'Combinatorics'), ('cs', 'Computer Science'), ('other', 'Other')], max_length=5),
        ),
    ]
