# Generated by Django 3.0.5 on 2020-05-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200515_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.CharField(max_length=2000),
        ),
    ]
