# Generated by Django 3.0.5 on 2020-05-19 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0006_auto_20200515_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='difficulty',
            field=models.SmallIntegerField(choices=[(1, 'Easy - Mid AMC'), (2, 'Easy AIME'), (3, 'Mid AIME'), (4, 'Hard AIME'), (5, 'USAMO')]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='quality',
            field=models.SmallIntegerField(choices=[(2, 'Definitely'), (1, 'Yes'), (0, 'Unsure'), (-1, 'No'), (-2, 'Definitely not')]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
