# Generated by Django 3.0.5 on 2020-05-23 02:54

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('database', '0007_auto_20200519_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
