# Generated by Django 3.0.5 on 2020-05-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_problem_tags'),
        ('database', '0008_auto_20200522_1857'),
    ]

    operations = [
    ]
