# Generated by Django 3.0.5 on 2020-11-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20200523_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_text',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
