# Generated by Django 3.2.7 on 2021-09-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20201130_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
